Horse.create!([
  {hname: "Admire Rakti", trainer: "Zac Purton (58.5kg)", odds: 6, assigned: false, bname: nil, hnumber: 1},
  {hname: "Cavalryman", trainer: "Craig Williams 57kg", odds: 31, assigned: false, bname: nil, hnumber: 2},
  {hname: "Fawkner", trainer: "Nicholas Hall 57kg", odds: 11, assigned: false, bname: nil, hnumber: 3},
  {hname: "Red Cadeaux", trainer: "Gerald Mosse 57kg", odds: 22, assigned: false, bname: nil, hnumber: 4},
  {hname: "Protectionist", trainer: "Ryan Moore 56.5kg", odds: 8.5, assigned: false, bname: nil, hnumber: 5},
  {hname: "Sea Moon", trainer: "Tommy Berry 56.5kg", odds: 201, assigned: false, bname: nil, hnumber: 6},
  {hname: "Seismos", trainer: "Craig Newitt 56kg", odds: 85, assigned: false, bname: nil, hnumber: 7},
  {hname: "Junoob", trainer: "Hugh Bowman 55.5kg", odds: 29, assigned: false, bname: nil, hnumber: 8},
  {hname: "Royal Diamond", trainer: "Steven Arnold 55.5kg", odds: 80, assigned: false, bname: nil, hnumber: 9},
  {hname: "Gatewood", trainer: "William Buick 55kg", odds: 81, assigned: false, bname: nil, hnumber: 10},
  {hname: "Mutual Regard", trainer: "Damien Oliver 55kg", odds: 13, assigned: false, bname: nil, hnumber: 11},
  {hname: "Who Shot Thebarman", trainer: "Glen Boss 55kg", odds: 26, assigned: false, bname: nil, hnumber: 12},
  {hname: "Willing Foe", trainer: "James McDonald 55kg", odds: 34, assigned: false, bname: nil, hnumber: 13},
  {hname: "My Ambivalent", trainer: "Andrea Atzeni 54.5kg", odds: 51, assigned: false, bname: nil, hnumber: 14},
  {hname: "Precedence", trainer: "Michael Rodd 54.5kg", odds: 151, assigned: false, bname: nil, hnumber: 15},
  {hname: "Brambles", trainer: "Luke Nolen 54kg", odds: 90, assigned: false, bname: nil, hnumber: 16},
  {hname: "Mr O'ceirin", trainer: "Chad Schofield 54kg", odds: 310, assigned: false, bname: nil, hnumber: 17},
  {hname: "Au Revoir", trainer: "Glyn Schofield 53.5kg", odds: 70, assigned: false, bname: nil, hnumber: 18},
  {hname: "Lidari", trainer: "Ben Melham 53.5kg", odds: 81, assigned: false, bname: nil, hnumber: 19},
  {hname: "Opinion", trainer: "Tye Angland 53.5kg", odds: 67, assigned: false, bname: nil, hnumber: 20},
  {hname: "Araldo", trainer: "Dwayne Dunn 53kg", odds: 34, assigned: false, bname: nil, hnumber: 21},
  {hname: "Lucia Valentina", trainer: "Kerrin McEvoy 53kg", odds: 8, assigned: false, bname: nil, hnumber: 22},
  {hname: "Unchain My Heart", trainer: "Dean Yendall 51.5kg", odds: 301, assigned: false, bname: nil, hnumber: 23},
  {hname: "Signoff", trainer: "Joao Moreira 51kg", odds: 8, assigned: false, bname: nil, hnumber: 24 }
])
