Horse.create!([
  {hname: "Admire Rakti", trainer: "Zac Purton (58.5kg)", odds: 6, assigned: false, bname: nil, hnumber: 1, sweep_id: 1},
  {hname: "Cavalryman", trainer: "Craig Williams 57kg", odds: 31, assigned: false, bname: nil, hnumber: 2, sweep_id: 1},
  {hname: "Fawkner", trainer: "Nicholas Hall 57kg", odds: 11, assigned: false, bname: nil, hnumber: 3, sweep_id: 1},
  {hname: "Red Cadeaux", trainer: "Gerald Mosse 57kg", odds: 22, assigned: false, bname: nil, hnumber: 4, sweep_id: 1},
  {hname: "Protectionist", trainer: "Ryan Moore 56.5kg", odds: 8, assigned: false, bname: nil, hnumber: 5, sweep_id: 1},
  {hname: "Sea Moon", trainer: "Tommy Berry 56.5kg", odds: 201, assigned: false, bname: nil, hnumber: 6, sweep_id: 1},
  {hname: "Seismos", trainer: "Craig Newitt 56kg", odds: 85, assigned: false, bname: nil, hnumber: 7, sweep_id: 1},
  {hname: "Junoob", trainer: "Hugh Bowman 55.5kg", odds: 29, assigned: false, bname: nil, hnumber: 8, sweep_id: 1},
  {hname: "Royal Diamond", trainer: "Steven Arnold 55.5kg", odds: 80, assigned: false, bname: nil, hnumber: 9, sweep_id: 1},
  {hname: "Gatewood", trainer: "William Buick 55kg", odds: 81, assigned: false, bname: nil, hnumber: 10, sweep_id: 1},
  {hname: "Mutual Regard", trainer: "Damien Oliver 55kg", odds: 13, assigned: false, bname: nil, hnumber: 11, sweep_id: 1},
  {hname: "Who Shot Thebarman", trainer: "Glen Boss 55kg", odds: 26, assigned: false, bname: nil, hnumber: 12, sweep_id: 1},
  {hname: "Willing Foe", trainer: "James McDonald 55kg", odds: 34, assigned: false, bname: nil, hnumber: 13, sweep_id: 1},
  {hname: "My Ambivalent", trainer: "Andrea Atzeni 54.5kg", odds: 51, assigned: false, bname: nil, hnumber: 14, sweep_id: 1},
  {hname: "Precedence", trainer: "Michael Rodd 54.5kg", odds: 151, assigned: false, bname: nil, hnumber: 15, sweep_id: 1},
  {hname: "Brambles", trainer: "Luke Nolen 54kg", odds: 90, assigned: false, bname: nil, hnumber: 16, sweep_id: 1},
  {hname: "Mr O'ceirin", trainer: "Chad Schofield 54kg", odds: 310, assigned: false, bname: nil, hnumber: 17, sweep_id: 1},
  {hname: "Au Revoir", trainer: "Glyn Schofield 53.5kg", odds: 70, assigned: false, bname: nil, hnumber: 18, sweep_id: 1},
  {hname: "Lidari", trainer: "Ben Melham 53.5kg", odds: 81, assigned: false, bname: nil, hnumber: 19, sweep_id: 1},
  {hname: "Opinion", trainer: "Tye Angland 53.5kg", odds: 67, assigned: false, bname: nil, hnumber: 20, sweep_id: 1},
  {hname: "Araldo", trainer: "Dwayne Dunn 53kg", odds: 34, assigned: false, bname: nil, hnumber: 21, sweep_id: 1},
  {hname: "Lucia Valentina", trainer: "Kerrin McEvoy 53kg", odds: 8, assigned: false, bname: nil, hnumber: 22, sweep_id: 1},
  {hname: "Unchain My Heart", trainer: "Dean Yendall 51.5kg", odds: 301, assigned: false, bname: nil, hnumber: 23, sweep_id: 1},
  {hname: "Signoff", trainer: "Joao Moreira 51kg", odds: 8, assigned: false, bname: nil, hnumber: 24, sweep_id: 1},
  {hname: "Admire Rakti", trainer: "Zac Purton (58.5kg)", odds: 6, assigned: false, bname: nil, hnumber: 1, sweep_id: 2},
  {hname: "Cavalryman", trainer: "Craig Williams 57kg", odds: 31, assigned: false, bname: nil, hnumber: 2, sweep_id: 2},
  {hname: "Fawkner", trainer: "Nicholas Hall 57kg", odds: 11, assigned: false, bname: nil, hnumber: 3, sweep_id: 2},
  {hname: "Red Cadeaux", trainer: "Gerald Mosse 57kg", odds: 22, assigned: false, bname: nil, hnumber: 4, sweep_id: 2},
  {hname: "Protectionist", trainer: "Ryan Moore 56.5kg", odds: 8, assigned: false, bname: nil, hnumber: 5, sweep_id: 2},
  {hname: "Sea Moon", trainer: "Tommy Berry 56.5kg", odds: 201, assigned: false, bname: nil, hnumber: 6, sweep_id: 2},
  {hname: "Seismos", trainer: "Craig Newitt 56kg", odds: 85, assigned: false, bname: nil, hnumber: 7, sweep_id: 2},
  {hname: "Junoob", trainer: "Hugh Bowman 55.5kg", odds: 29, assigned: false, bname: nil, hnumber: 8, sweep_id: 2},
  {hname: "Royal Diamond", trainer: "Steven Arnold 55.5kg", odds: 80, assigned: false, bname: nil, hnumber: 9, sweep_id: 2},
  {hname: "Gatewood", trainer: "William Buick 55kg", odds: 81, assigned: false, bname: nil, hnumber: 10, sweep_id: 2},
  {hname: "Mutual Regard", trainer: "Damien Oliver 55kg", odds: 13, assigned: false, bname: nil, hnumber: 11, sweep_id: 2},
  {hname: "Who Shot Thebarman", trainer: "Glen Boss 55kg", odds: 26, assigned: false, bname: nil, hnumber: 12, sweep_id: 2},
  {hname: "Willing Foe", trainer: "James McDonald 55kg", odds: 34, assigned: false, bname: nil, hnumber: 13, sweep_id: 2},
  {hname: "My Ambivalent", trainer: "Andrea Atzeni 54.5kg", odds: 51, assigned: false, bname: nil, hnumber: 14, sweep_id: 2},
  {hname: "Precedence", trainer: "Michael Rodd 54.5kg", odds: 151, assigned: false, bname: nil, hnumber: 15, sweep_id: 2},
  {hname: "Brambles", trainer: "Luke Nolen 54kg", odds: 90, assigned: false, bname: nil, hnumber: 16, sweep_id: 2},
  {hname: "Mr O'ceirin", trainer: "Chad Schofield 54kg", odds: 310, assigned: false, bname: nil, hnumber: 17, sweep_id: 2},
  {hname: "Au Revoir", trainer: "Glyn Schofield 53.5kg", odds: 70, assigned: false, bname: nil, hnumber: 18, sweep_id: 2},
  {hname: "Lidari", trainer: "Ben Melham 53.5kg", odds: 81, assigned: false, bname: nil, hnumber: 19, sweep_id: 2},
  {hname: "Opinion", trainer: "Tye Angland 53.5kg", odds: 67, assigned: false, bname: nil, hnumber: 20, sweep_id: 2},
  {hname: "Araldo", trainer: "Dwayne Dunn 53kg", odds: 34, assigned: false, bname: nil, hnumber: 21, sweep_id: 2},
  {hname: "Lucia Valentina", trainer: "Kerrin McEvoy 53kg", odds: 8, assigned: false, bname: nil, hnumber: 22, sweep_id: 2},
  {hname: "Unchain My Heart", trainer: "Dean Yendall 51.5kg", odds: 301, assigned: false, bname: nil, hnumber: 23, sweep_id: 2},
  {hname: "Signoff", trainer: "Joao Moreira 51kg", odds: 8, assigned: false, bname: nil, hnumber: 24, sweep_id: 2},
  {hname: "Admire Rakti", trainer: "Zac Purton (58.5kg)", odds: 6, assigned: false, bname: nil, hnumber: 1, sweep_id: 3},
  {hname: "Cavalryman", trainer: "Craig Williams 57kg", odds: 31, assigned: false, bname: nil, hnumber: 2, sweep_id: 3},
  {hname: "Fawkner", trainer: "Nicholas Hall 57kg", odds: 11, assigned: false, bname: nil, hnumber: 3, sweep_id: 3},
  {hname: "Red Cadeaux", trainer: "Gerald Mosse 57kg", odds: 22, assigned: false, bname: nil, hnumber: 4, sweep_id: 3},
  {hname: "Protectionist", trainer: "Ryan Moore 56.5kg", odds: 8, assigned: false, bname: nil, hnumber: 5, sweep_id: 3},
  {hname: "Sea Moon", trainer: "Tommy Berry 56.5kg", odds: 201, assigned: false, bname: nil, hnumber: 6, sweep_id: 3},
  {hname: "Seismos", trainer: "Craig Newitt 56kg", odds: 85, assigned: false, bname: nil, hnumber: 7, sweep_id: 3},
  {hname: "Junoob", trainer: "Hugh Bowman 55.5kg", odds: 29, assigned: false, bname: nil, hnumber: 8, sweep_id: 3},
  {hname: "Royal Diamond", trainer: "Steven Arnold 55.5kg", odds: 80, assigned: false, bname: nil, hnumber: 9, sweep_id: 3},
  {hname: "Gatewood", trainer: "William Buick 55kg", odds: 81, assigned: false, bname: nil, hnumber: 10, sweep_id: 3},
  {hname: "Mutual Regard", trainer: "Damien Oliver 55kg", odds: 13, assigned: false, bname: nil, hnumber: 11, sweep_id: 3},
  {hname: "Who Shot Thebarman", trainer: "Glen Boss 55kg", odds: 26, assigned: false, bname: nil, hnumber: 12, sweep_id: 3},
  {hname: "Willing Foe", trainer: "James McDonald 55kg", odds: 34, assigned: false, bname: nil, hnumber: 13, sweep_id: 3},
  {hname: "My Ambivalent", trainer: "Andrea Atzeni 54.5kg", odds: 51, assigned: false, bname: nil, hnumber: 14, sweep_id: 3},
  {hname: "Precedence", trainer: "Michael Rodd 54.5kg", odds: 151, assigned: false, bname: nil, hnumber: 15, sweep_id: 3},
  {hname: "Brambles", trainer: "Luke Nolen 54kg", odds: 90, assigned: false, bname: nil, hnumber: 16, sweep_id: 3},
  {hname: "Mr O'ceirin", trainer: "Chad Schofield 54kg", odds: 310, assigned: false, bname: nil, hnumber: 17, sweep_id: 3},
  {hname: "Au Revoir", trainer: "Glyn Schofield 53.5kg", odds: 70, assigned: false, bname: nil, hnumber: 18, sweep_id: 3},
  {hname: "Lidari", trainer: "Ben Melham 53.5kg", odds: 81, assigned: false, bname: nil, hnumber: 19, sweep_id: 3},
  {hname: "Opinion", trainer: "Tye Angland 53.5kg", odds: 67, assigned: false, bname: nil, hnumber: 20, sweep_id: 3},
  {hname: "Araldo", trainer: "Dwayne Dunn 53kg", odds: 34, assigned: false, bname: nil, hnumber: 21, sweep_id: 3},
  {hname: "Lucia Valentina", trainer: "Kerrin McEvoy 53kg", odds: 8, assigned: false, bname: nil, hnumber: 22, sweep_id: 3},
  {hname: "Unchain My Heart", trainer: "Dean Yendall 51.5kg", odds: 301, assigned: false, bname: nil, hnumber: 23, sweep_id: 3},
  {hname: "Signoff", trainer: "Joao Moreira 51kg", odds: 8, assigned: false, bname: nil, hnumber: 24, sweep_id: 3}

])
Sweep.create!([
  {value: 2},
  {value: 5},
  {value: 10}
              ])
